version: '3.4'

services:
  ourservice:
    hostname: ourservice
    image: ourservice
    build:
      context: ./OurService/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - "ASPNETCORE_URLS=http://localhost:5001;https://localhost:5002"
