version: '3.4'

networks:
  network1:
    name: network1

services:
  wiremock:
    container_name: wiremock
    hostname: wiremock
    image: rodolpheche/wiremock
    command: "--verbose"
    ports:
      - 8080:8080
    volumes:
      - ./IntegrationTests/wiremock/mappings:/home/wiremock/mappings
    networks:
      - network1

  ourservice:
    container_name: ourservice
    hostname: ourservice
    image: ourservice
    build:
      context: ./OurService/
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - VENDOR_URL=http://wiremock:8080
    networks:
      - network1
    depends_on:
      - wiremock

