version: '3.4'

networks:
  network1:
    name: network1

services:
  ourservice:
    container_name: ourservice
    hostname: ourservice
    image: ourservice
    build:
      context: ./OurService/
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000
    networks:
      - network1
